feat(15-matrices): adding fail-fast

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -18,6 +18,9 @@ jobs:
         include:
           - os: ubuntu-latest
             node-version: 16.x
+          - os: ubuntu-latest
+            node-version: 21.x
+            tag: experimental
 
     steps:
       - name: Setup node
@@ -25,6 +28,16 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
 
+      - name: Fail if experimental
+        if: matrix.tag == 'experimental'
+        run: |
+          echo "Failing experimental job"
+          exit 1
+
       - name: Perform some test
         run: |
           echo "Running tests on OS: ${{matrix.os}} and NodeJS ${{ matrix.node-version }}"
+          sleep 10
+
+      - name: Upload test results
+        run: echo "Uploading test results"
